name: 'Summarized Status'
description: |
  Summarize Status multiple CIs (like Github Actions workflow).
  Useful when you want to use `Require status checks to pass before merging` with monorepo (paths).
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
